### ISSUE TITLE
Sign-in sheet: adding an invalid phone number causes confusing UI behavior

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/swoptact#89] opened 2015-06-10 23:52 UTC
If you put an invalid phone number in the Phone Number field on the Sign-in Sheet, and then hit Done, nothing happens.  You are not allowed to save the row (good), but you also are not given any helpful error messages or wayfinding to the source of the problem (bad).

To reproduce, just go to Events -> "Demo Event", edit the row for "Daria Lagos" on the Sign-in Sheet, put "1345" for the phone number, and click Done.

(See also issue #51, which is about displaying phone numbers with correct phone-number format, though that may end up not being relevant for how we fix this issue.)

**Comment by cecilia-donnelly** [comment] 2015-06-11 14:36
Possible duplicate of #63.

**Closed** 2015-06-19 18:18 UTC
