### ISSUE TITLE
Sign-in sheet: Add separate row with optional information

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#45] opened 2015-05-19 15:38 UTC
Most sign-in sheets will include only name, phone number, and institution.  Some others will have more information, and users would like these fields to appear in an option row below the main row, for each attendee.  This optional row will include only address, for now, but users may request more fields going forward.

The row should appear on click of a "more" icon, and be editable/viewable in the same way(s) as the main row.

**Comment by kfogel** [comment] 2015-06-10 23:15
We closed this because we're not doing it, right?  That is, I don't think it was ever implemented, and the issue is closed, so... I'm just checking that the justification for the closing is what I think it is.

**Comment by cecilia-donnelly** [comment] 2015-06-11 14:39
@kfogel it looks like you closed this?  I think it should still be open, though perhaps it will go in the "Beta" milestone (not the next demo).  I think they will most likely want some way to enter these other fields (e.g. address) in the sign-in sheet.

**Comment by cecilia-donnelly** [comment] 2015-07-17 19:21
@kfogel per our conversation with them yesterday, can we close this?  I think the link to the profile does what they wanted this to do.

**Closed** 2015-08-07 17:17 UTC
