### ISSUE TITLE
Sign-in sheet: Remove "link existing", offer autocompletion in "add new" row

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#48] opened 2015-05-19 16:00 UTC
Currently, we have two different buttons to add a Participant to an Action via the sign-in sheet.  "Link existing" works for Participants that already exist in the system, and "Add new" creates a new Participant in the system and connects that new Participant to the Action. 

This distinction should disappear.  When a user clicks "Add new," they'll see a new blank row (just as they do currently).  The difference is that when they start typing, autocomplete will show them existing participants that match the substring(s) they've typed into the various fields.  If one of those matches and the user selects it, then that existing Participant should be linked to the Action.  If none of the existing Participants matches, then save the new Participant and link it to the Action.

**Comment by cwebber** [comment] 2015-06-07 16:07
Since we wrote the inline ajax'y stuff from scratch, unfortunately we will probably also have to implement this autocomplete code from scratch... I will investigate, but I suspect autocomplete_light is mostly not compatible with it, since that requires appending things to Django's form objects, and we are building up the forms from scratch in javascript here.

I'll see if any parts can be reused.

**Comment by cwebber** [comment] 2015-06-07 18:37
Good news everyone!  We'll have to write some custom JS (expected) but it looks like the django autocomplete library is pretty modular in its api and with the registry works.  Pleasantly:

```
Here is the list of the major difference with other autocomplete scripts:

- don't do anything but fire a signal when a choice is selected: it's
left as an exercise to the developer to implement whatever he wants when
that happens
- don't generate the autocomplete HTML, it should be generated by the server
```

(The above from comments in autocomplete.js)

Giving this a shot.

**Comment by cwebber** [comment] 2015-06-07 21:34
Arg, I wrote a long followup to this but I accidenatlly closed my browser. :(

The long of it is that I'm investigating it, but it's pretty tricky since we generate those fields ourselves.  If using python to generate the form, we'd get to take advantage of this logic for free, but right now I'm trying to reconstruct what it is.

This is what [Django renders through](https://github.com/yourlabs/django-autocomplete-light/blob/master/autocomplete_light/templates/autocomplete_light/widget.html), which is really heavy and hard to wrap my brain around.  However I've now discovered the [docs for the javascript side of things](https://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/script.html) and am going through those.

**Comment by cecilia-donnelly** [comment] 2015-06-08 23:58
Some clarification on the desired behavior, as I look at the screen with @kfogel: 

First, when a user is entering a participant let's autocomplete the first and last names (if possible) to save keystrokes.  This is separate from the question of whether they're linking an existing Participant or creating a new one.  Second, if first and last names match one or more existing Participants then we need to show some kind of selector UI that has at a minimum 2 choices: the first choice is "No, I'm creating a new Participant" (paraphrase wildly) and the remaining choice(s) are all the matching participants with name, phone number, and institution.

This selector UI should appear inline at and below the row where they are working so that it's easy for them to see and quick to use.

**Comment by cwebber** [comment] 2015-06-10 00:35
This is taking some time, so thought I'd clarify what's going on.

Initially, I was unable to access any of the autocomplete methods.  It turned out this was for the very same reason that the autocomplete of the standard forms was not working on this page: we imported jquery several times, blowing away the jquery extensions as the jquery object was replaced with something new each time.  So that is done and out of the way.  What now?

So adding the dropdown via what appears to be the recommended method of the [scripts documentation](https://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/script.html) does indeed result in a dropdown, and you can see this in the branch I started for the issue 48 stuff that isn't ready yet.  However, hovering over the autocomplete stuff does not become blue, and clicking the appropriate element fails to trigger the callback set up for selectChoice, even though I've done pretty much exactly what the tutorial has said.

So I tried pasting the same kind of structure that the django template generates right onto the page:

``` html
  <span data-widget-ready="1" id="id_contact-wrapper"
        class="autocomplete-light-widget contact single"
        data-widget-bootstrap="normal" data-widget-maximum-values="1">
      <span id="id_contact-deck" class="deck">
      </span>

      <input autocomplete="off" name="contact-autocomplete" id="id_contact-autocomplete"
             value="" class=" autocomplete vTextField"
             data-autocomplete-choice-selector="[data-value]" data-autocomplete-minimum-characters="1"
             data-autocomplete-url="/autocomplete/ContactAutocomplete/" placeholder="" type="text">
      
      <select style="display:none" class="value-select"
              name="contact" id="id_contact" multiple="multiple">
      </select>
      
      <span style="display:none" class="remove">
          ˣ
      </span>

      <span style="display:none" class="choice-template">
          <span class="choice prepend-remove append-option-html">
          </span>
      </span>
  </span>
```

This indeed results in the blue hover and appears capable of a callback, though I assume it's a callback tailored pretty much exactly for synchronizing with the django forms' assumptions because that's what [widget.js more or less says](https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/widget.js).  So okay, I guess I'll read exactly the [entire danged javascript code for autocomplete.js](https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/autocomplete.js).  Well, I've done this, reading this top to bottom, and I'm still lost.

Since the django stuff works, I figure it should be possible to mime that output and *maybe* we could hack it into something that works, but I'm really hesitant to do that.  widget.js talks about coordinating with the django backend and doing some magic involving some sort of extra magical attributes and I just don't know how it works.  I'm afraid we'll run into some unexpected behavior and I don't know what to do about that.

So, I'm still stuck at this point of writing, though I've got a much deeper understanding of what's going on... though still no clue why that callback is not being invoked.

**Comment by kfogel** [comment] 2015-06-10 17:50
As per IRC conversation with @cwebber today:

After this issue is completed, a new issue should be created to do similar autocomplete for Institution (e.g., on the Sign-in sheet) as well.  It should be a separate ticket, but the technique we use for solving this issue will be the same one we use for solving that one as well.

**Comment by cwebber** [comment] 2015-06-18 16:42
One confusing thing is that the hover selection box that appears I was fairly certain was using autocomplete.js only and that widget.js was only for Django related things or structures using those assumptions.  However, this appears not to be true: the hovering selection box that appears appears to contain the autocomplete-light-widget class, not defined in anything other than widget.js.  So my assumptions there were wrong.

Still not sure why we can't interact by clicking or hovering on that box.  That's the blocker to completing this.

**Comment by cwebber** [comment] 2015-06-18 19:52
My last comment was wrong in its first part, the autocomplete-light-widget class isn't being set on this.  But the inability to trigger on hover / click events is still true.

It might have to do with the absolute positioning hack it uses.  I'm not really sure.

Sorry this is taking so long.  I'm really confused as to why this doesn't work.  I might move onto a different library soon... I don't think many people are doing the "just use the js library part" direction.

**Comment by cwebber** [comment] 2015-06-18 23:20
See the comment I made in #94.  I've been running my head into this long enough, going to try a go with jquery-autocomplete but utilizing the same backend things we already have.

**Comment by cwebber** [comment] 2015-06-20 20:40
Good news!  This is complete and now merged with master.  We moved towards using jquery-ui's autocomplete stuff and this resulted in this turning around much faster.

Horray!

**Closed by cwebber** 2015-06-20 20:40 UTC
Labels: high priority
