### ISSUE TITLE
Sign-in sheet: editing Institution field has no effect.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/swoptact#87] opened 2015-06-10 23:27 UTC
When you edit a Participant's row in the Sign-in Sheet interface, any changes you make to the Institution field will not be saved.  This is true whether the field was previously empty or had data, and it is true whether the Institution name you type is the name of an existing Institution or is just some random string.

This bug was already known as of [this comment on #13](https://github.com/OpenTechStrategies/swoptact/issues/13#issuecomment-94592333), but when that issue got broken out into multiple tickets this bug accidentally got dropped, I think.

Anyway: clearly, we want our jet-age autocomplete behavior to apply to this Institution field.  When the user types, the matches for existing institutions should be chooseable, and if in the end the user enters some string that isn't a match, then a new Institution should be created with that name, with the rest of its information to be filled in some other time (perhaps "Show incomplete Institutions" will be a desired report some day).  This is related to / the same as the autocomplete behavior for Participants as discussed in issue #48 and (I guess) issue #54.

See also issue #78 -- whatever our behavior is here, it should probably be the same there.

**Comment by kfogel** [comment] 2015-06-10 23:48
By the way, just to save us time spelunking, I think probably this function in `swoptact/static/js/inline_ajax.js` is where this would be fixed:

    /*
     takes a participant object and returns a participant object filled with new
     values from the input fields in that participant's row
     */
    function updateParticipant(participant){
        if (participant.id){
            var edit_input = $('#participant-edit-'+participant.id);
        }
        else{
            var edit_input = $('#participant-edit-');
        }
        var text_inputs = (edit_input.find(".vTextField"));
        // array will be name, phone_number, address as long as our
        // UI columns stay the same
        participant.name = text_inputs[0].value;
        participant.primary_phone = text_inputs[2].value;
        return participant;
    }

As you can see, the comment inside the function is _already_ out of date, and we don't use the value of `text_inputs[1]` at all.

**Comment by cecilia-donnelly** [comment] 2015-06-12 18:26
Note the conditional mentioned in #83, which I closed as a duplicate of this issue.

**Comment by cwebber** [comment] 2015-06-20 20:43
Assigning to myself.

**Comment by cwebber** [comment] 2015-06-20 20:54
There's some subtle but tricky aspects to getting the behavior right.  I'll implement it as specified above, and it's easy enough if a user selects an institution that already exists.  But consider:

 - A user may change a single character, which they may believe means they are changing the name of the institution that *already exists*, believing they are editing that existing institution.  But clearly they won't... they'll be adding a new institution.
 - Many "partial" institutions may be unintentionally added, or worse, if a user manually types out a name many times rather than selecting from the dropdown, many copies of that institution may be selected.

I'm worried that's not the behavior we want.  I imagine that being an edge that user will cut themselves on many times.

The UI I think would be *better* would be to have the institution normally be a dropdown selection, but if a user hits a pencil (yes, I know we've been trying to get rid of those) they can mark to add a new institution.

Otherwise I'm afraid we're going to result in the cruft accumulation problems I've mentioned above.

But hey, what do I know? :)

**Comment by cwebber** [comment] 2015-06-22 19:35
@cecilia-donnelly and I talked on IRC and I think we came to some good ways forward on this.  But first, some clarity on why the institution field has this issue but the current implementation of the rest of the participant selection on this page does not!

The way that selecting a participant via autocomplete currently works doesn't have the above ambiguiities because there's a clear distinction between these phases: "adding new / selecting existing", "linked to the model but static / not being edited", and finally "editing something that's already linked" phases.  Though the first and last phases both support a similar looking editing mode, it takes a user action to "transform" the static form into the being-edited form, and when being edited, there is no autocomplete given, since we already know what this foreign key links to.

So, knowing that above, how can we get similar ideas to apply to the above?  I thought of a way that requires no dropdown.

When a user hits edit, all fields become editable *except* the institution field, to which suddenly an edit button or pencil or etc will appear.  Hitting this button gives a textbox, and the user has one of two options: start typing something for the autocomplete (this will initialize a dropdown and also add a [+] button to the right of the box subtly indicating that a change is happening) and the user can either select one of these from the dropdown to link an existing participant, or select to the right where either a [+] or an [x] button exists to either add this as a new participant or cancel.  The user is *not* given the option of changing the name of the institution... that will only lead to ambiguities in the user interface which as far as I can tell are unresolvable.  (I'm open to hearing otherwise!)

How does this sound?  @kfogel, thoughts?

**Comment by cecilia-donnelly** [comment] 2015-06-24 16:23
A relevant screenshot from @cwebber, for @kfogel: http://dustycloud.org/tmp/institution_on_participants.png

**Comment by cwebber** [comment] 2015-06-24 22:35
So we had some conversation about this on IRC today, and came up with a new strategy:

 - Make the name field of institution models unique
 - When typing out an insitution, it'll do autocomplete for that institution, and when the user types out an institution that does not exist, we'll leave an indicator that it's new, maybe even with a `[new]` marker that's green or something.
 - Upon save, either use the institution whose name matches the text input, or make a new institution and link that.

I'll get to work on this!

**Comment by cwebber** [comment] 2015-07-01 04:42
So it's nearly midnight here and I'm too tired to make further headway here, but *progress update time!*

Right now you can now do autocomplete on the institution fields.  When it's a new institution, a green "[NEW]" appears, which @cecilia-donnelly says looks good, so great, horray horrah!  *That* part is in master.

However saving institutions doesn't exactly work.  I knew this might be stepping in @xray7224's territory, so I started pushing ot a new branch, 87-edit_institution.  As of fe51c0a things are so-close-but-not-there.  It seems like I'm linking up the institution, even creating if necessary, but the foreign key link doesn't seem to be doing anything.  I'm a bit lost.

@xray7224 could you look at this with me tomorrow?  And take a look at the approach I took to the API stuff?  I'd love your input!

**Comment by cecilia-donnelly** [comment] 2015-07-01 14:43
@cwebber hurray!  Congrats!  I'll leave it in your and @xray7224's capable hands. :+1:

**Comment by cwebber** [comment] 2015-07-01 20:18
Done!  Thanks to @xray7224 for helping me figure out that I needed to add "institution" to the "fields" attribute on ParticipantAPI.  Whew!

**Closed by cwebber** 2015-07-01 20:18 UTC
Labels: high priority
