### ISSUE TITLE
Inlined models: Errors never clear now

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#178] opened 2015-08-27 18:45 UTC
Previous workflow would result in different states between editing a row, saving it, and switching to a static view.  There was an error row shown when things went wrong, but it would also be hidden from view when switching back to static mode, and would also be removed and refilled at specific points in the code.

There now appears to be no changes that will remove the errors now.  One solution is to move the work to clear errors away from workflow as it was before and onto the action of the user: give "close" widgets to each error after it has been reviewed.

Also, after editing and changing a row, this should certainly clear its errors.

(Possibly a separate issue, but I also saw two rows swap, and I'm not sure why, and so the error row was no longer hovering above the row it was intended to represent.  This may be a separate issue.)

**Comment by nttaylor** [comment] 2015-09-01 20:48
Can maybe be closed following 070ac87 but requires further testing. I also have not observed the "row swapping" described by @cwebber above. Can that error be recreated?

I also think I remember seeing another place in the code where a row was being `remove()`d without grabbing its associated error row, but I didn't touch that on this commit. Worth keeping an eye on.

**Comment by cecilia-donnelly** [comment] 2015-09-02 14:52
@nttaylor this is separate from #177 (though your point about removing the error row along with its visible counterpart is a good one!).  For this issue, try adding an invalid phone number to an existing attendee.  An error row will appear, and clicking to edit a different row will not remove it.  I believe that the error can be removed by removing the offending item, but I think that @cwebber's point is that it should disappear when the user is apparently not editing the erroring row anymore.

**Comment by cecilia-donnelly** [comment] 2015-09-04 17:23
@nttaylor is changing the error display on the inline ajax models such that the errors show up inside each `td`, so that it's clear to a user where exactly the problem is when they get an error.  When one cell in a row has an error, the rest of the row is highlighted and cannot be edited.  This has to do with specifics of the API: currently the entire object is updated, not just one field.  So, if one field is invalid, the whole object is made in-editable.

As of c45f578, this is working in most cases.   However, when the user edits the institution and then adds an invalid phone number, the error does not appear.
Ex: 
```
| Joe Random |                              |               |
// becomes
| Joe Random | Elementary School Institution |  5555        |
// and does not error on invalid phone number (though the text input remains open after click away)
```

**Comment by nttaylor** [comment] 2015-09-04 18:16
The above actually exposes an error not inherent to the new behavior but on that was already present in the code and unnoticed until now. This error has been given a new issue #186.

**Comment by cecilia-donnelly** [comment] 2015-09-11 18:58
@nttaylor, can this be closed?  It's merged and deployed, so I'm going to close it.  Feel free to reopen if you know something that I don't.

**Closed by cecilia-donnelly** 2015-09-11 18:58 UTC
